### ISSUE TITLE
game crashes

### ISSUE THREAD

**Issue by BasieEnAdriaan** [gbl/AdvancementInfo#3]
when I put the file in my mods folder the game crashes on startup. Is there a solution for this?

**Comment by gbl** [comment]
I need the Minecraft log file, can't figure out anything without that.

**Comment by BasieEnAdriaan** [comment]
Do you mean this?
<img width="1002" alt="Schermafbeelding 2021-02-28 om 10 11 29" src="https://user-images.githubusercontent.com/79771182/109413377-5f4b3700-79ad-11eb-85c3-10de244b429a.png">

**Comment by BasieEnAdriaan** [comment]
Oh wait now my game starts up but the advancement tab didn't change

**Comment by gbl** [comment]
No, I need the minecraft log file. It's in the logs folder, next to the "mods" folder.

**Comment by BasieEnAdriaan** [comment]
Oh you mean this?
[latest.log](https://github.com/gbl/AdvancementInfo/files/6068102/latest.log)

**Comment by gbl** [comment]
Yes, that's what I need. The line that solves the problem is this one:

net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: advancementinfo requires {fabric @ [*]}

You need the Fabric API as well (like for almost all mods), from https://modrinth.com/mod/fabric-api/versions or https://www.curseforge.com/minecraft/mc-mods/fabric-api/files (make sure you download the correct version for your Minecraft).
